### ISSUE TITLE
Add ability to reload the page using cmd/ctrl+r

### ISSUE THREAD

**Issue by pomdtr** [hamza72x/nativefier_tauri#11]

**Comment by hamza72x** [comment]
Thanks for your issues. I was also thinking to fix those, but being lazy...you know.

Will go through them.

**Comment by pomdtr** [comment]
You're welcome ! You can take inspiration from https://github.com/tw93/Pake/blob/master/README_EN.md it support most of those features (the default icon is quite strange though 😅).

**Comment by hamza72x** [comment]
I have found that project after creating this, then I though creating this was time waste. Since that's more mature and both has same goal.

**Comment by hamza72x** [comment]
@pomdtr Added, please install latest cli :)

![image](https://user-images.githubusercontent.com/48919542/224457590-52f744fa-55dd-4373-88df-cd6677fc00d7.png)
