### ISSUE TITLE
Ability to change user agent?

### ISSUE THREAD

**Issue by tm1000** [hamza72x/nativefier_tauri#14]
See: https://github.com/tauri-apps/tauri/issues/4284

It would be nice to be able to change user agent

**Comment by hamza72x** [comment]
Added `-g`  or `--user-agent` flag argument.

```sh
nativefier_tauri args -n Google -u https://google.com -g cat
```

![image](https://user-images.githubusercontent.com/48919542/224485967-dee7b112-b33c-4272-aa09-33cc55f5d2cc.png)
