### ISSUE TITLE
Suggestion: remove positional args

### ISSUE THREAD

**Issue by pomdtr** [hamza72x/nativefier_tauri#16]
The `args` vs `interactive` subcommands are confusing.

What about: 
- having a single `nativefier_tauri` command without any subcommands
- showing a prompts when a required param was not provided as a flag

ex:

```bash
nativefier_tauri # will show all of the prompts
nativier_tauri --url google.com # will show all the prompts except the url one
```

**Comment by hamza72x** [comment]
Thanks for issue. But the main reason for splitting these 2 was to split complete bahavior, not to use within interchange.

**Comment by pomdtr** [comment]
Since the final action is the same (creating an app),  it makes no sense to have two separate commands.

Instead, having a single command that can be called either interactively or non-interactively is a common pattern (`npm init` is a good example).

**Comment by hamza72x** [comment]
Thank you, but it's rather subjective choice. And not trying to make it more complex for this simple tool. I hope you don't mind.
