### ISSUE TITLE
Google-Chat app

### ISSUE THREAD

**Issue by mjabdulm** [hamza72x/nativefier_tauri#23]
Hi I'm trying to create a google-chat app using web2app but I'm getting an error that the web browser is not supported. The notifier version of the app works fine. 

Any suggestions/guidance is appreciated.

**Comment by hamza72x** [comment]
Use custom `user-agent` (try using Chrome's latest user-agent) while building the app.

Example:

```sh
web2app -u <url> -n <name> -g "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15"
```

**Comment by mjabdulm** [comment]
Thanks a lot. It did work fine now.

I'm seeing a huge memory usage when compared to electron version of google-chat-app.

Am I missing something?
Also, could you please guide me on :
how to inject custom js and css files while building the app?
how hide the title bar?

Cheers,
Abdul

**Comment by hamza72x** [comment]
1. tauri uses the native webkit. You can find similar ram usage in safari if you check `Activity Monitor`.

<img width="358" alt="image" src="https://github.com/hamza72x/web2app/assets/48919542/df58bc0f-bffb-4eef-be43-fb7b7a1685f0">

2. Custom js and css is not possible yet

3. Not possible for the time being.

**Comment by mjabdulm** [comment]
Thanks a lot for the feedback. I’ll try it for a few weeks.
