### ISSUE TITLE
error[E0433]: failed to resolve: use of undeclared crate or module `webkit2gtk`

### ISSUE THREAD

**Issue by Natetronn** [hamza72x/nativefier_tauri#24]
Hi, I'm getting webkit2gtk errors on an arch based system when running the following command :

`web2app args -n myappname -u http://myapp:1234 -i myapplogo.png`

Note: Your previous version (nativefier_tauri) worked perfectly fine on this same machine with the exact same setup, as I have webkit2gtk-4.0 (and 4.1) installed and I ran `sudo pacman -S webkit2gtk` to make sure it was indeed installed, per the previous docs and as suggested in this issue: https://github.com/hamza72x/web2app/issues/7

```
error[E0433]: failed to resolve: use of undeclared crate or module `webkit2gtk`
  --> src/util.rs:12:21
   |
12 |                 use webkit2gtk::traits::WebViewExt;
   |                     ^^^^^^^^^^ use of undeclared crate or module `webkit2gtk`

error[E0599]: no method named `set_zoom_level` found for struct `Rc<webkit2gtk::auto::web_view::WebView>` in the current scope
  --> src/util.rs:13:33
   |
13 |                 webview.inner().set_zoom_level(factor);
   |                                 ^^^^^^^^^^^^^^ method not found in `Rc<WebView>`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  + use webkit2gtk::auto::web_view::WebViewExt;
   |

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `audiobookshelf` (bin "audiobookshelf") due to 2 previous errors
       Error failed to build app: failed to build app
    /wdusb/Applications/Web2App  kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found 
```

```
lrwxrwxrwx 1 root root    23 May  1 12:23 libwebkit2gtk-4.0.so -> libwebkit2gtk-4.0.so.37
lrwxrwxrwx 1 root root    28 May  1 12:23 libwebkit2gtk-4.0.so.37 -> libwebkit2gtk-4.0.so.37.63.2
-rwxr-xr-x 1 root root   60M May  1 12:23 libwebkit2gtk-4.0.so.37.63.2
lrwxrwxrwx 1 root root    22 May  1 12:46 libwebkit2gtk-4.1.so -> libwebkit2gtk-4.1.so.0
lrwxrwxrwx 1 root root    26 May  1 12:46 libwebkit2gtk-4.1.so.0 -> libwebkit2gtk-4.1.so.0.8.2
-rwxr-xr-x 1 root root   60M May  1 12:46 libwebkit2gtk-4.1.so.0.8.2
drwxr-xr-x 1 root root   130 Jun 24 10:45 webkit2gtk-4.0
drwxr-xr-x 1 root root   130 Jun  4 10:36 webkit2gtk-4.1

```
![webkit2gtk-4 0](https://github.com/hamza72x/web2app/assets/582149/61999ffb-a35b-45e2-bdf1-474a10931aa4)

Any thoughts, by chance?

**Comment by hamza72x** [comment]
I forgot to add/adjust the template's `Cargo.toml` to add `webkit2gtk` as dependency (for linux). So some changes are required (which I found while playing with Asahi Linux)

But didn't have enough time to solve. Maybe, I can have a answer by tomorrow. If you wouldn't get reply, then please ping again. Very busy now-a-days, horrible time management.

**Comment by Natetronn** [comment]
@hamza72x thank you for the quick reply! Okay, I understand and appreciate your time. I'll check in again soon. Have a nice day.

**Comment by hamza72x** [comment]
@Natetronn partially fixed. Now you can build the executable with new version (published to crate too, just update the package)

But, arch packaging will fail due to this pending PR: https://github.com/tauri-apps/tauri/pull/4301

Again, you still will be able to run the executable from: `$HOME/web2app_apps/<app_name>/target/release/<executable>`

btw, it's required to pass `-i` icon parameter

**Comment by Natetronn** [comment]
@hamza72x great, thank you very much! 

I just installed the lastest update via the crate command in the docs and it looks like it's working well now.

I see it created the executable, plus some extras; AppImage, deb, everything in the /usr directory etc.

That arch pr looks interesting.

Yes, I pass the -i flag to each application out of habit either way (always did so with Nativefier as well.)
