### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }'

### ISSUE THREAD

**Issue by MrConnorKenway** [hamza72x/nativefier_tauri#6]
Version 0.1.9
The program crashed at src/main.rs line 120:
```rust
    // convert
    print_and_wait("\n🎉 Checking if convert is installed...");
    util::run_os_command("convert -version", None).unwrap();
```
Where should I get this `convert`?

**Comment by hamza72x** [comment]
Sorry, I should have mentioned in Readme.

You need to install `imagemagick` tool.

Usually almost all package manager has this tool. For example:

```sh
# macOS
brew install imagemagick

# apt
sudo apt install imagemagick
```

The `convert` comes with this package.
