### ISSUE TITLE
Allow to pass arguments as flags

### ISSUE THREAD

**Issue by pomdtr** [hamza72x/nativefier_tauri#9]
The interactive installer is good, but I would prefer to be able to pass those info as command line flags. 

I'm the autor of https://github.com/sunbeamlauncher/sunbeam, I would like to create an integration for the app, but it requires to be able to use it without an interaction.

**Comment by hamza72x** [comment]
```sh
nativefier_tauri args -n Notion -u https://www.notion.so -i icon.png
```

Added flags support :)
